/** A curated set of emoji for the insert picker. Emoji are plain Unicode
 * characters, so they render with the operating system's own colour emoji font
 * (Apple Color Emoji, Segoe UI Emoji, Noto, …) both in the picker and on the
 * Konva canvas — we lean on the OS glyphs rather than bundling artwork.
 *
 * `keywords` (English) drive client-side search filtering. */
export type EmojiCategory =
  | 'smileys'
  | 'people'
  | 'animals'
  | 'food'
  | 'activities'
  | 'travel'
  | 'objects'
  | 'symbols'
  | 'flags';

export interface EmojiItem {
  char: string;
  keywords: string;
  category: EmojiCategory;
}

/** Display order of the picker sections. */
export const EMOJI_CATEGORY_ORDER: EmojiCategory[] = [
  'smileys',
  'people',
  'animals',
  'food',
  'activities',
  'travel',
  'objects',
  'symbols',
  'flags',
];

function group(category: EmojiCategory, entries: [string, string][]): EmojiItem[] {
  return entries.map(([char, keywords]) => ({ char, keywords, category }));
}

export const EMOJI_LIBRARY: EmojiItem[] = [
  ...group('smileys', [
    ['😀', 'grin smile happy face'],
    ['😁', 'beaming grin happy'],
    ['😂', 'joy laugh tears lol'],
    ['🤣', 'rofl rolling laughing'],
    ['😊', 'blush smile happy'],
    ['😍', 'heart eyes love'],
    ['🥰', 'love hearts adore'],
    ['😘', 'kiss love blow'],
    ['😎', 'cool sunglasses'],
    ['🤩', 'star struck excited wow'],
    ['🤔', 'thinking hmm consider'],
    ['😏', 'smirk sly'],
    ['😢', 'cry sad tear'],
    ['😭', 'sob crying sad'],
    ['😡', 'angry mad rage'],
    ['🥳', 'party celebrate hat'],
    ['😱', 'scream shock fear'],
    ['🤯', 'mind blown explode'],
    ['😴', 'sleep tired zzz'],
    ['🙄', 'eye roll annoyed'],
    ['😅', 'sweat nervous laugh'],
    ['🥺', 'pleading puppy eyes beg'],
    ['😇', 'angel halo innocent'],
    ['🤗', 'hug hands smile'],
  ]),
  ...group('people', [
    ['👍', 'thumbs up like approve yes'],
    ['👎', 'thumbs down dislike no'],
    ['👏', 'clap applause bravo'],
    ['🙌', 'raise hands celebrate praise'],
    ['🙏', 'pray thanks please hands'],
    ['💪', 'muscle strong flex'],
    ['👋', 'wave hello hi bye'],
    ['🤝', 'handshake deal agree'],
    ['✌️', 'peace victory two'],
    ['🤞', 'fingers crossed luck hope'],
    ['👌', 'ok perfect good'],
    ['👀', 'eyes look watch see'],
    ['🧠', 'brain smart mind'],
    ['❤️', 'heart love red'],
    ['🫶', 'heart hands love'],
    ['👶', 'baby child'],
    ['🧑‍💻', 'developer coder laptop tech'],
    ['🕺', 'dance man party'],
    ['💃', 'dance woman party'],
  ]),
  ...group('animals', [
    ['🐶', 'dog puppy pet'],
    ['🐱', 'cat kitten pet'],
    ['🦊', 'fox'],
    ['🐻', 'bear'],
    ['🐼', 'panda'],
    ['🦁', 'lion'],
    ['🐯', 'tiger'],
    ['🐮', 'cow'],
    ['🐷', 'pig'],
    ['🐸', 'frog'],
    ['🐵', 'monkey'],
    ['🦄', 'unicorn magic'],
    ['🐝', 'bee honey'],
    ['🦋', 'butterfly'],
    ['🐢', 'turtle slow'],
    ['🐙', 'octopus'],
    ['🐬', 'dolphin'],
    ['🦖', 'dinosaur trex'],
    ['🌸', 'flower blossom cherry'],
    ['🌻', 'sunflower flower'],
    ['🌹', 'rose flower love'],
    ['🌿', 'leaf herb plant'],
    ['🌵', 'cactus plant'],
    ['🌈', 'rainbow pride'],
  ]),
  ...group('food', [
    ['🍕', 'pizza food slice'],
    ['🍔', 'burger food'],
    ['🍟', 'fries food'],
    ['🌮', 'taco food'],
    ['🍣', 'sushi food'],
    ['🍩', 'donut sweet'],
    ['🍪', 'cookie sweet'],
    ['🎂', 'cake birthday'],
    ['🍰', 'cake slice sweet'],
    ['🍫', 'chocolate sweet'],
    ['🍦', 'ice cream sweet'],
    ['🍎', 'apple fruit'],
    ['🍌', 'banana fruit'],
    ['🍓', 'strawberry fruit'],
    ['🍉', 'watermelon fruit'],
    ['☕', 'coffee drink hot'],
    ['🍵', 'tea drink hot'],
    ['🍺', 'beer drink'],
    ['🍷', 'wine drink'],
    ['🥂', 'cheers champagne celebrate'],
  ]),
  ...group('activities', [
    ['⚽', 'soccer football ball sport'],
    ['🏀', 'basketball ball sport'],
    ['🏈', 'football ball sport'],
    ['⚾', 'baseball ball sport'],
    ['🎾', 'tennis ball sport'],
    ['🏆', 'trophy win award'],
    ['🥇', 'gold medal first win'],
    ['🎯', 'target dart goal'],
    ['🎮', 'game controller play'],
    ['🎲', 'dice game luck'],
    ['🎨', 'art paint palette'],
    ['🎵', 'music note song'],
    ['🎤', 'mic sing karaoke'],
    ['🎧', 'headphones music'],
    ['🎬', 'movie film clapper'],
    ['📸', 'camera photo'],
    ['🎉', 'party celebrate tada'],
    ['🎁', 'gift present'],
  ]),
  ...group('travel', [
    ['✈️', 'plane travel flight'],
    ['🚀', 'rocket launch space'],
    ['🚗', 'car drive'],
    ['🚕', 'taxi car'],
    ['🚲', 'bike bicycle'],
    ['🏠', 'house home'],
    ['🏢', 'office building'],
    ['🌍', 'earth world globe'],
    ['🗺️', 'map travel'],
    ['🏝️', 'island beach vacation'],
    ['🏔️', 'mountain snow'],
    ['🌃', 'city night skyline'],
    ['🌅', 'sunrise sun'],
    ['⛺', 'tent camping'],
    ['📍', 'pin location place'],
    ['🧭', 'compass navigate'],
  ]),
  ...group('objects', [
    ['💡', 'idea lightbulb bright'],
    ['🔥', 'fire hot lit trending'],
    ['⭐', 'star favourite'],
    ['✨', 'sparkles shine magic new'],
    ['💥', 'boom explosion collision'],
    ['💯', 'hundred perfect score'],
    ['📱', 'phone mobile'],
    ['💻', 'laptop computer'],
    ['⌚', 'watch time'],
    ['📷', 'camera photo'],
    ['💰', 'money bag cash'],
    ['💳', 'card credit pay'],
    ['🔑', 'key lock access'],
    ['🔒', 'lock secure'],
    ['📌', 'pin note tack'],
    ['📎', 'paperclip attach'],
    ['✏️', 'pencil write edit'],
    ['📚', 'books read study'],
    ['🎈', 'balloon party'],
    ['🕯️', 'candle light'],
  ]),
  ...group('symbols', [
    ['✅', 'check tick done yes'],
    ['❌', 'cross x no wrong'],
    ['❗', 'exclamation alert'],
    ['❓', 'question help'],
    ['⚠️', 'warning caution'],
    ['➕', 'plus add'],
    ['➖', 'minus subtract'],
    ['➡️', 'arrow right next'],
    ['⬅️', 'arrow left back'],
    ['⬆️', 'arrow up'],
    ['⬇️', 'arrow down'],
    ['🔝', 'top up'],
    ['💬', 'speech comment chat'],
    ['💭', 'thought bubble'],
    ['♻️', 'recycle eco green'],
    ['🆕', 'new badge'],
    ['🔔', 'bell notification alert'],
    ['💲', 'dollar money price'],
    ['©️', 'copyright'],
    ['™️', 'trademark'],
  ]),
  ...group('flags', [
    ['🏳️', 'white flag'],
    ['🏴', 'black flag'],
    ['🏁', 'checkered finish race'],
    ['🚩', 'red triangular flag'],
    ['🏳️‍🌈', 'rainbow pride lgbt flag'],
    ['🇺🇸', 'united states america usa flag'],
    ['🇬🇧', 'united kingdom uk britain england flag'],
    ['🇫🇷', 'france french flag'],
    ['🇩🇪', 'germany german deutschland flag'],
    ['🇪🇸', 'spain spanish españa flag'],
    ['🇮🇹', 'italy italian italia flag'],
    ['🇵🇹', 'portugal portuguese flag'],
    ['🇳🇱', 'netherlands dutch holland flag'],
    ['🇧🇪', 'belgium belgian flag'],
    ['🇨🇭', 'switzerland swiss flag'],
    ['🇮🇪', 'ireland irish flag'],
    ['🇸🇪', 'sweden swedish flag'],
    ['🇳🇴', 'norway norwegian flag'],
    ['🇩🇰', 'denmark danish flag'],
    ['🇫🇮', 'finland finnish flag'],
    ['🇵🇱', 'poland polish flag'],
    ['🇬🇷', 'greece greek flag'],
    ['🇺🇦', 'ukraine ukrainian flag'],
    ['🇷🇺', 'russia russian flag'],
    ['🇹🇷', 'turkey turkish flag'],
    ['🇨🇦', 'canada canadian flag'],
    ['🇲🇽', 'mexico mexican flag'],
    ['🇧🇷', 'brazil brazilian brasil flag'],
    ['🇦🇷', 'argentina argentine flag'],
    ['🇨🇳', 'china chinese flag'],
    ['🇯🇵', 'japan japanese flag'],
    ['🇰🇷', 'south korea korean flag'],
    ['🇮🇳', 'india indian flag'],
    ['🇦🇺', 'australia australian flag'],
    ['🇳🇿', 'new zealand flag'],
    ['🇿🇦', 'south africa african flag'],
    ['🇪🇬', 'egypt egyptian flag'],
    ['🇳🇬', 'nigeria nigerian flag'],
    ['🇸🇦', 'saudi arabia arabian flag'],
    ['🇦🇪', 'united arab emirates uae flag'],
    ['🇪🇺', 'european union europe eu flag'],
  ]),
];
