import {
  CURRENT_SCHEMA_VERSION,
  type CalqoProject,
} from './schema';

/** Bundled editable alpha sample. It is offered from the empty state and only
 * persisted after the user opens it. The missing raster blob intentionally
 * produces an export diagnostic so testers see the readiness path. */
export function createSampleProject(now = new Date().toISOString()): CalqoProject {
  return {
    schemaVersion: CURRENT_SCHEMA_VERSION,
    id: 'proj_alpha_sample',
    name: 'Calqo alpha sample',
    createdAt: now,
    updatedAt: now,
    contentLocales: ['en', 'fr', 'tr'],
    activeContentLocale: 'en',
    palette: ['#0A2540', '#FFFFFF', '#E8B339', '#007AFF'],
    assets: [
      {
        id: 'asset_sample_missing_photo',
        kind: 'raster',
        name: 'sample-photo-placeholder.png',
        mimeType: 'image/png',
        width: 2200,
        height: 1800,
        storageKey: 'asset_sample_missing_photo',
        createdAt: now,
      },
    ],
    glossary: [
      {
        source: 'Calqo',
        mode: 'do-not-translate',
        notes: 'Product name.',
      },
    ],
    artboards: [
      {
        id: 'ab_alpha_sample_square',
        name: 'Instagram square',
        preset: 'ig-square',
        width: 1080,
        height: 1080,
        background: {
          type: 'linear',
          angle: 135,
          stops: [
            { offset: 0, color: '#0A2540' },
            { offset: 1, color: '#102F57' },
          ],
        },
        layers: [
          {
            id: 'sample_photo',
            name: 'Campaign photo placeholder',
            type: 'image',
            assetId: 'asset_sample_missing_photo_blob',
            x: 600,
            y: 106,
            w: 420,
            h: 560,
            rotation: 0,
            opacity: 1,
            visible: true,
            locked: false,
            fit: 'cover',
            mask: { shape: 'rounded', radius: 42 },
            effects: {
              shadow: {
                color: '#000000',
                blur: 28,
                offsetX: 0,
                offsetY: 18,
                opacity: 0.22,
              },
            },
          },
          {
            id: 'sample_badge',
            name: 'Launch badge',
            type: 'shape',
            shape: 'rect',
            x: 92,
            y: 96,
            w: 282,
            h: 64,
            rotation: 0,
            opacity: 1,
            visible: true,
            locked: false,
            fill: { type: 'solid', color: '#E8B339' },
            cornerRadius: 28,
          },
          {
            id: 'sample_badge_text',
            name: 'Badge text',
            type: 'text',
            x: 126,
            y: 113,
            w: 230,
            h: 34,
            rotation: 0,
            opacity: 1,
            visible: true,
            locked: false,
            text: {
              en: 'PUBLIC ALPHA',
              fr: 'ALPHA PUBLIQUE',
              tr: 'AÇIK ALFA',
            },
            style: {
              fontFamily: 'Inter',
              fontSize: 25,
              fontWeight: 800,
              color: '#0A2540',
              align: 'center',
              lineHeight: 1,
              letterSpacing: 0.5,
            },
          },
          {
            id: 'sample_title',
            name: 'Headline',
            type: 'text',
            x: 92,
            y: 230,
            w: 560,
            h: 250,
            rotation: 0,
            opacity: 1,
            visible: true,
            locked: false,
            text: {
              en: 'Make the post. Keep the layers.',
              fr: 'Créez le post. Gardez les calques.',
              tr: 'Gönderiyi tasarla. Katmanları koru.',
            },
            style: {
              fontFamily: 'Inter',
              fontSize: 78,
              fontWeight: 800,
              color: '#FFFFFF',
              align: 'left',
              lineHeight: 1.02,
              letterSpacing: -0.2,
            },
          },
          {
            id: 'sample_body',
            name: 'Body copy',
            type: 'text',
            x: 96,
            y: 548,
            w: 520,
            h: 126,
            rotation: 0,
            opacity: 1,
            visible: true,
            locked: false,
            text: {
              en: 'A local-first social visual maker with editable AI templates and per-locale content.',
              fr: 'Un éditeur local-first pour visuels sociaux, avec modèles IA modifiables et contenu par langue.',
              tr: 'Düzenlenebilir yapay zeka şablonları ve dile göre içerik sunan yerel öncelikli sosyal görsel aracı.',
            },
            style: {
              fontFamily: 'Inter',
              fontSize: 34,
              fontWeight: 500,
              color: '#DDEBFF',
              align: 'left',
              lineHeight: 1.18,
              letterSpacing: 0,
            },
          },
          {
            id: 'sample_cta',
            name: 'CTA card',
            type: 'shape',
            shape: 'rect',
            x: 92,
            y: 782,
            w: 508,
            h: 120,
            rotation: 0,
            opacity: 1,
            visible: true,
            locked: false,
            fill: { type: 'solid', color: '#FFFFFF' },
            cornerRadius: 34,
          },
          {
            id: 'sample_cta_text',
            name: 'CTA text',
            type: 'text',
            x: 130,
            y: 817,
            w: 432,
            h: 52,
            rotation: 0,
            opacity: 1,
            visible: true,
            locked: false,
            text: {
              en: 'Export PNG, SVG, HTML',
              fr: 'Export PNG, SVG, HTML',
              tr: 'PNG, SVG, HTML dışa aktar',
            },
            style: {
              fontFamily: 'Inter',
              fontSize: 34,
              fontWeight: 750,
              color: '#0A2540',
              align: 'center',
              lineHeight: 1.15,
              letterSpacing: 0,
            },
          },
          {
            id: 'sample_overflow_note',
            name: 'Export warning demo',
            type: 'shape',
            shape: 'rect',
            x: 1010,
            y: 1010,
            w: 150,
            h: 60,
            rotation: 0,
            opacity: 0.2,
            visible: true,
            locked: false,
            fill: { type: 'solid', color: '#E8B339' },
            cornerRadius: 18,
          },
        ],
      },
    ],
  };
}
